baseurl = "https://xiangyun.rbind.io/"
languageCode = "zh-CN"
title = "Xiangyun Huang | 黄湘云"
theme = "hugo-lithium"
googleAnalytics = "G-WF0Y8H10PV"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 9
rssLimit = 10

[permalinks]
  [permalinks.page]
    post = '/:year/:month/:slug/'
    daily = '/:year/:month/:slug/'
    business = '/:year/:month/:slug/'
  [permalinks.section]
    post = '/post/'
    daily = '/daily/'
    business = '/business/'

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "博客"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "日志"
    url = "/daily/"
    weight = 3
[[menu.main]]
    name = "商业"
    url = "/business/"
    weight = 4
[[menu.main]]
    name = "书籍"
    url = "/book/"
    weight = 5
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 6

[params]
    description = "A website built through Hugo and blogdown."

    customCSS = ["css/custom.css"]
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml", "tex", "matlab", "mathematica"]
    highlightjsTheme = "github"
    fontawesomeVersion = "4.7.0"
    fontawesomeCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"

    GithubEdit = "https://github.com/rbind/xiangyun/edit/master/content/"

[markup]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.highlight]
      codeFences = false
    [markup.tableOfContents]
      startLevel = 1
